CREATE TABLE eldis_cms.cms_categories (
  id INT(11) NOT NULL AUTO_INCREMENT,
  cat_title VARCHAR(255) DEFAULT NULL,
  status INT(2) NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 1;

CREATE TABLE eldis_cms.cms_comments (
  comment_id INT(11) NOT NULL AUTO_INCREMENT,
  comment_post_id INT(11) DEFAULT NULL,
  comment_author INT(11) DEFAULT NULL,
  comment_content VARCHAR(255) DEFAULT NULL,
  comment_status INT(2) NOT NULL DEFAULT 1,
  comment_date TIMESTAMP NOT NULL DEFAULT current_timestamp(),
  comment_parent_id INT(11) DEFAULT NULL,
  comment_count INT(4) DEFAULT NULL,
  PRIMARY KEY (comment_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 1;

CREATE TABLE eldis_cms.cms_games_titles (
  id INT(11) NOT NULL AUTO_INCREMENT,
  game_name VARCHAR(255) DEFAULT NULL,
  rating INT(2) DEFAULT NULL,
  status INT(2) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 1;

CREATE TABLE eldis_cms.cms_landing (
  id INT(11) NOT NULL AUTO_INCREMENT,
  text_slideshow INT(11) DEFAULT NULL,
  header VARCHAR(255) DEFAULT NULL,
  row1_img VARCHAR(255) DEFAULT NULL,
  row1_header VARCHAR(25) DEFAULT NULL,
  row1_content TEXT DEFAULT NULL,
  row1_button VARCHAR(25) DEFAULT NULL,
  row1_button_href VARCHAR(255) DEFAULT NULL,
  row2_img VARCHAR(255) DEFAULT NULL,
  row2_header VARCHAR(25) DEFAULT NULL,
  row2_content TEXT DEFAULT NULL,
  row2_button VARCHAR(25) DEFAULT NULL,
  row2_button_href VARCHAR(255) DEFAULT NULL,
  row3_img VARCHAR(255) DEFAULT NULL,
  row3_header VARCHAR(25) DEFAULT NULL,
  row3_content TEXT DEFAULT NULL,
  row3_button VARCHAR(255) DEFAULT NULL,
  row3_button_href VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 1;

CREATE TABLE eldis_cms.cms_posts (
  id INT(11) NOT NULL AUTO_INCREMENT,
  category_id INT(11) DEFAULT NULL,
  post_title VARCHAR(255) DEFAULT NULL,
  post_author VARCHAR(255) DEFAULT NULL,
  post_author_image VARCHAR(255) DEFAULT NULL,
  post_author_image_alt VARCHAR(255) DEFAULT NULL,
  post_date TIMESTAMP NOT NULL DEFAULT current_timestamp(),
  post_image TEXT DEFAULT NULL,
  post_image_alt VARCHAR(255) DEFAULT NULL,
  post_content TEXT DEFAULT NULL,
  post_comment_count INT(11) DEFAULT NULL,
  post_tags VARCHAR(255) DEFAULT NULL,
  post_status INT(11) NOT NULL DEFAULT 2,
  user_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 1;

CREATE TABLE eldis_cms.cms_status_types (
  id INT(11) NOT NULL AUTO_INCREMENT,
  status_name VARCHAR(25) DEFAULT NULL,
  status_type VARCHAR(25) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 1;

CREATE TABLE eldis_cms.cms_text_slideshow (
  id INT(11) NOT NULL AUTO_INCREMENT,
  header VARCHAR(155) DEFAULT NULL,
  subheader VARCHAR(155) DEFAULT NULL,
  slideshow INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 1;

CREATE TABLE eldis_cms.cms_users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  role INT(1) NOT NULL DEFAULT 1,
  image VARCHAR(255) NOT NULL DEFAULT 'default_user.jpg',
  title VARCHAR(25) DEFAULT NULL,
  firstname VARCHAR(255) DEFAULT NULL,
  lastname VARCHAR(255) DEFAULT NULL,
  about VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 1;

CREATE TABLE eldis_cms.cms_users_categories (
  id INT(11) NOT NULL AUTO_INCREMENT,
  user_id INT(11) DEFAULT NULL,
  cat_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 1;


CREATE TABLE eldis_cms.cms_users_games (
  id INT(11) NOT NULL AUTO_INCREMENT,
  game_id INT(11) DEFAULT NULL,
  user_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 1;




--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 11/25/2020 2:19:59 PM
-- Server version: 5.5.5-10.4.14-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO eldis_cms.cms_categories(id, cat_title) VALUES
(1, 'MMO FPS'),
(7, 'Single Player FPS'),
(8, 'MMO RP Games'),
(14, 'MMO Arena'),
(18, 'MMO Battlegrounds'),
(19, 'Platforming Games'),
(20, 'Simulation Games'),
(22, 'MMO Raids');


INSERT INTO eldis_cms.cms_comments(comment_id, comment_post_id, comment_author, comment_content, comment_status, comment_date, comment_parent_id, comment_count) VALUES
(9, 2, 1, 'This completely changed the game.', 2, '2020-11-09 16:43:18', 9, NULL),
(12, 2, 1, 'I like the new patch.', 2, '2020-11-10 14:19:41', 0, NULL),
(18, 2, 1, 'Man, the speed of leveling is insane.', 2, '2020-11-10 14:30:55', 0, NULL),
(21, 1, 1, 'Call of Duty franchise has always been good.', 2, '2020-11-11 17:52:46', 0, NULL),
(23, 1, 1, 'I am rock n roll.', 3, '2020-11-16 19:16:37', 0, NULL),
(29, 1, 1, 'I''m a badass.', 3, '2020-11-18 19:03:45', 0, NULL),
(31, 1, 18, 'this is dude.', 3, '2020-11-18 22:20:23', 0, NULL),
(33, 1, 18, 'Well okeedokee.', 2, '2020-11-19 16:29:45', 0, NULL),
(34, 1, 19, 'I like fps.', 2, '2020-11-24 11:10:43', 0, NULL);


INSERT INTO eldis_cms.cms_games_titles(id, game_name, rating) VALUES
(1, 'World of Warcraft', NULL),
(2, 'World of Warcraft Classic', NULL),
(3, 'Overwatch', NULL),
(4, 'Hearthstone', NULL),
(5, 'Warcraft III', NULL),
(6, 'Diablo III', NULL),
(7, 'Heroes of the Storm', NULL),
(8, 'StarCraft II', NULL),
(9, 'StarCraft', NULL),
(10, 'Call of Duty: MW', NULL),
(11, 'Call of Duty: MW2CR', NULL),
(12, 'Call of Duty: BO4', NULL),
(13, 'Call of Duty: BOCW', NULL),
(14, 'Battlefield 4', NULL),
(15, 'Battlefield 1', NULL),
(16, 'Battlefield V', NULL);


INSERT INTO eldis_cms.cms_posts(id, category_id, post_title, post_author, post_author_image, post_author_image_alt, post_date, post_image, post_image_alt, post_content, post_tags, post_comment_count, post_status) VALUES
(1, 1, 'Call of Duty Black Ops 4', 'Blizzard', 'blizzard.png', 'Blizzard Entertainment', '2020-10-29 19:03:57', 'black_ops_4.jpg', 'Black Ops 4', '<p>For the first time, Call of Duty®: Black Ops 4 is coming to Blizzard Battle.net in a fully-optimized for PC experience and fully integrated into Battle.net social features. Developed in partnership between Treyarch and Beenox, Call of Duty®: Black Ops 4 will be the most robust, refined, and customizable PC shooter experience we’ve ever created. Features include uncapped framerate, 4K resolution, HDR, support for ultrawide monitors and additional features built for the PC community.</p>', 'blizzard, call of duty, black ops, black ops 4', 17, 2),
(2, 8, 'World of Warcraft Patch 9.0.1', 'Blizzard', 'blizzard.png', 'Blizzard Entertainment', '2020-10-29 19:42:17', 'shadowlands_header.jpg', 'The Shadowlands', null, 'blizzard, world of warcraft, alliance, horde', 3, 2);


INSERT INTO eldis_cms.cms_status_types(id, status_name, status_type) VALUES
(1, 'draft', 'post'),
(2, 'publish', 'post'),
(3, 'removed', 'post');


INSERT INTO eldis_cms.cms_users(id, username, email, password, role, image, title, firstname, lastname, about) VALUES
(1, 'eldis', '3eldis@gmail.com', '$2y$07$zhxd5jS6PfdsghrY1I5dheWA6ZqkhLZEqsHQzd75nYI6bBLqNbHei', 5, '1805.jpeg', 'Site Developer', 'Buddy', 'Rice', 'I mostly play World of Warcraft. My main right now is a warrior, Brudic on Area 52.'),
(18, 'dude', 'jwayne@wert.com', '$2y$07$zhxd5jS6PfdsghrY1I5dheWA6ZqkhLZEqsHQzd75nYI6bBLqNbHei', 4, 'skullpencil_large.jpg', 'The Duke', 'John', 'Wayne', NULL),
(19, 'cms_sys', 'drice@wert.com', '$2y$07$zhxd5jS6PfdsghrY1I5dheWA6ZqkhLZEqsHQzd75nYI6bBLqNbHei', 3, 'Elliot_PETES-DRAGON_RichB.png', 'Da Man', 'David', 'Rice', NULL);


INSERT INTO eldis_cms.cms_users_categories(id, user_id, cat_id) VALUES
(1, 1, 1),
(2, 1, 8);


INSERT INTO eldis_cms.cms_users_games(id, game_id, user_id) VALUES
(1, 1, 1),
(2, 2, 1),
(3, 14, 1),
(4, 15, 1),
(5, 16, 1);